/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplicationmultithread;


import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Pelin
 */
public final class TableSenaryo2  implements Runnable{
    private int data;
    private int aralik;
    float oran;
    String sutunbenzerlik;
    String sutunAyni;
    String istenensutun;

    JTable tablemodel;
    int Row;
    JavaList array;
    /**
     * Creates new form TableSenoryo1
     */
    public TableSenaryo2() {
    
       
      

    }

  public TableSenaryo2(int data,int aralik,float oran,String sutunbenzerlik ,JavaList Array,String sutunAyni,String istenenSutun) {
         this.data= data;
        this.aralik=aralik;
        this.oran=oran;
        this.sutunbenzerlik=sutunbenzerlik;
        this.array=Array;
        this.sutunAyni=sutunAyni;
        this.istenensutun=istenenSutun;
       
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    @Override
    public void run() {
  
        try {
            
	            
	                 Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/bigdata", "root", "mysql26");
                           PreparedStatement st = (PreparedStatement) connection
	                         .prepareStatement("Select * from bigdata.table1  where table1.index >= ? and table1.index <= ?");
                                 st.setInt(1,0);
                                 st.setInt(2,this.aralik);
                                                              
                           ResultSet rs2 = st.executeQuery(); 
                       
                           
                            
                            
               while (rs2.next() ) {
                 String product=rs2.getString(sutunAyni);
                 String benzerlik=rs2.getString(sutunbenzerlik);
                 String istenen=rs2.getString(istenensutun);
                 int index=rs2.getInt("index");   
                 if(this.data>index){
                         PreparedStatement st2 = (PreparedStatement) connection
	                         .prepareStatement("Select * from bigdata.table1  where table1.index> ? and table1.index <= ?");
                               st2.setInt(1,(this.data));
                               st2.setInt(2,(this.aralik));
	                    ResultSet rs3 = st2.executeQuery(); 
                          
                    while (rs3.next()) {
                       int num=0;
                       String cmpproduct=rs3.getString(sutunAyni);
                       String cmpbenzerlik=rs3.getString(sutunbenzerlik);
                       String cmpistenen=rs3.getString(istenensutun);

                      if(product.equals(cmpproduct)){
             

                             int cmplen=cmpbenzerlik.split("\\s+").length;
                       int prolen=benzerlik.split("\\s+").length;
                       String[] a = cmpbenzerlik.split("\\s+");
                       String[] b =benzerlik.split("\\s+");
                   
    for (int k = 0; k < a.length; k++) {
                   for (int j = 0; j < b.length; j++) {
                           if (!(k>=cmplen) && !(j>=prolen)) {
                               if(a[k].equals(b[j])){
                                     k++;  
             
              num++;
                               }
            
          }
      }
  }
                 //System.out.print(num);
                 if(cmplen>=prolen){
                     if(oran<=(Float.parseFloat(java.math.BigDecimal.valueOf((float)(((float)num/(float)cmplen)*100)).setScale(1,RoundingMode.HALF_UP).toString()))){
                         String data[]={String.valueOf(product),String.valueOf(cmpproduct),String.valueOf(benzerlik),String.valueOf(cmpbenzerlik),String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))),String.valueOf(istenen),String.valueOf(cmpistenen)};    
                            this.array.senaryo2.add(data);
                                                //    System.out.println(product+" "+cmpproduct+" "+benzerlik+" "+cmpbenzerlik+" "+istenen+" "+cmpistenen+" "+String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))));

                     
                     }
                         
                     //  System.out.println(product+" "+cmpproduct+" "+(float)(((float)num/(float)cmplen)*100));
                   }else{
                      if(oran<=(Float.parseFloat(java.math.BigDecimal.valueOf((float)(((float)num/(float)prolen)*100)).setScale(1,RoundingMode.HALF_UP).toString()))){
                         String data[]={String.valueOf(product),String.valueOf(cmpproduct),String.valueOf(benzerlik),String.valueOf(cmpbenzerlik),String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))),String.valueOf(istenen),String.valueOf(cmpistenen)};    
                            this.array.senaryo2.add(data);
                          //  System.out.println(product+" "+cmpproduct+" "+benzerlik+" "+cmpbenzerlik+" "+istenen+" "+cmpistenen+" "+String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))));

                     }
                                                                      
                                          //  System.out.println(product+" "+cmpproduct+" "+(float)(((float)num/(float)prolen)*100));
 
                   } 
                          
                      }
                                            //  System.out.println(" "+product+" "+cmpproduct+" ");       
  
                   
                  
                  
                 
                      
                   
              
                 }
                 }else if(this.data<=index){
                         PreparedStatement st2 = (PreparedStatement) connection
	                         .prepareStatement("Select * from bigdata.table1  where table1.index> ? and table1.index <= ?");
                               st2.setInt(1,(index));
                               st2.setInt(2,(this.aralik));
	                    ResultSet rs3 = st2.executeQuery(); 
                       while (rs3.next()) {
                       int num=0;
                       String cmpproduct=rs3.getString(sutunAyni);
                       String cmpbenzerlik=rs3.getString(sutunbenzerlik);
                       String cmpistenen=rs3.getString(istenensutun);

                      if(product.equals(cmpproduct)){
                          
                             int cmplen=cmpbenzerlik.split("\\s+").length;
                       int prolen=benzerlik.split("\\s+").length;
                       String[] a = cmpbenzerlik.split("\\s+");
                       String[] b =benzerlik.split("\\s+");
                            
    for (int k = 0; k < a.length; k++) {
                   for (int j = 0; j < b.length; j++) {
                           if (!(k>=cmplen) && !(j>=prolen)) {
                               if(a[k].equals(b[j])){
                                     k++;  
              
              num++;
                               }
            
          }
      }
  }
                 //System.out.print(num);
                 if(cmplen>=prolen){
                     if(oran<=(Float.parseFloat(java.math.BigDecimal.valueOf((float)(((float)num/(float)cmplen)*100)).setScale(1,RoundingMode.HALF_UP).toString()))){
                         String data[]={String.valueOf(product),String.valueOf(cmpproduct),String.valueOf(benzerlik),String.valueOf(cmpbenzerlik),String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))),String.valueOf(istenen),String.valueOf(cmpistenen)};    
                          //  System.out.println(product+" "+cmpproduct+" "+benzerlik+" "+cmpbenzerlik+" "+istenen+" "+cmpistenen+" "+String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))));
                         this.array.senaryo2.add(data);
                        
                     
                     }
                         
                     //  System.out.println(product+" "+cmpproduct+" "+(float)(((float)num/(float)cmplen)*100));
                   }else{
                      if(oran<=(Float.parseFloat(java.math.BigDecimal.valueOf((float)(((float)num/(float)prolen)*100)).setScale(1,RoundingMode.HALF_UP).toString()))){
                         String data[]={String.valueOf(product),String.valueOf(cmpproduct),String.valueOf(benzerlik),String.valueOf(cmpbenzerlik),String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))),String.valueOf(istenen),String.valueOf(cmpistenen)};    
                                                    //  System.out.println(product+" "+cmpproduct+" "+benzerlik+" "+cmpbenzerlik+" "+istenen+" "+cmpistenen+" "+String.valueOf(Float.toString((float)(((float)num/(float)cmplen)*100))));

                         this.array.senaryo2.add(data);

                     }
                                                                      
                                          //  System.out.println(product+" "+cmpproduct+" "+(float)(((float)num/(float)prolen)*100));
 
                   } 
                          
                      }
                                            //  System.out.println(" "+product+" "+cmpproduct+" ");       
  
                   
                  
                  
                 
                      
                   
              
                 }
               
            }

                  
           
                
                
               }

                                
                                   
	                  
                                                   

            
                   }catch (SQLException sqlException) {
	                    sqlException.printStackTrace();
	                }
        
       
       
    }
    
}
